name: AEMET mirror

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    env:
      AEMET_API_KEY: ${{ secrets.AEMET_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }

      - run: npm install --no-audit --no-fund

      # Generar ficheros (si AEMET falla, los scripts escriben FeatureCollection vacía)
      - run: node scripts/fetch_avisos.js
      - run: node scripts/fetch_obs.js

      - run: mkdir -p dist && touch dist/.nojekyll && ls -l dist

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - uses: actions/deploy-pages@v4

        with:
          path: dist
      - uses: actions/deploy-pages@v4

