name: AEMET mirror

on:
  schedule:
    - cron: "*/10 * * * *"   # cada 10 minutos
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    env:
      AEMET_API_KEY: ${{ secrets.AEMET_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # instala dependencias
      - run: npm install --no-audit --no-fund

      # ejecuta scripts
      - run: node scripts/fetch_avisos.js
      - run: node scripts/fetch_obs.js

      # DEBUG: mostrar qué se ha generado en dist/
      - run: |
          echo "=== DIST LISTING ==="
          ls -l dist
          echo "=== HEAD avisos_diag.json ==="
          (test -f dist/avisos_diag.json && head -n 50 dist/avisos_diag.json) || echo "avisos_diag.json NO EXISTE"
          echo "=== HEAD obs_diag.json ==="
          (test -f dist/obs_diag.json && head -n 50 dist/obs_diag.json) || echo "obs_diag.json NO EXISTE"

      # necesario para que Pages publique también ficheros sin extensión .html
      - run: mkdir -p dist && touch dist/.nojekyll


      - name: Descargar y extraer avisos AEMET (tar.gz)
        run: |
          mkdir -p dist aemet_tmp
          curl -L "https://www.aemet.es/es/geojson/download/avisos/geojson_1759165200.tar.gz" -o aemet.tar.gz
          tar -xzf aemet.tar.gz -C aemet_tmp
          echo "Ficheros descargados:" && find aemet_tmp -type f -name '*.geojson' -maxdepth 2

      - name: Unir avisos AEMET a un solo GeoJSON
        run: |
          jq -s '{type:"FeatureCollection",features: map(.features) | add}' aemet_tmp/**/*.geojson > dist/avisos_aemet.geojson
          jq -c . dist/avisos_aemet.geojson > dist/avisos_aemet.min.geojson && mv dist/avisos_aemet.min.geojson dist/avisos_aemet.geojson
          jq '.features|length as $n | {features:$n, sample:(.[0]|.properties)}' dist/avisos_aemet.geojson > dist/avisos_aemet_diag.json


      # subir artefacto a GitHub Pages

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      # desplegar en Pages
      - uses: actions/deploy-pages@v4



