name: AEMET mirror

on:
  schedule:
    - cron: "*/10 * * * *"   # cada 10 minutos
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    env:
      AEMET_API_KEY: ${{ secrets.AEMET_API_KEY }}
      METEOALARM_TOKEN: ${{ secrets.METEOALARM_TOKEN }}  # <-- NUEVO
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }

      - run: npm install --no-audit --no-fund

      - run: node scripts/fetch_avisos.js
      - run: node scripts/fetch_obs.js

      - run: mkdir -p dist && touch dist/.nojekyll && ls -l dist

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - uses: actions/deploy-pages@v4

      - run: node scripts/fetch_avisos.js
      - run: node scripts/fetch_obs.js

      # DEBUG: Lista y enseña los ficheros que vamos a publicar
      - run: |
          echo "=== DIST LISTING ==="
          ls -l dist
          echo "=== HEAD obs_diag.json ==="
          (test -f dist/obs_diag.json && head -n 50 dist/obs_diag.json) || echo "obs_diag.json NO EXISTE"
          echo "=== HEAD avisos_diag.json ==="
          (test -f dist/avisos_diag.json && head -n 50 dist/avisos_diag.json) || echo "avisos_diag.json NO EXISTE"

      - run: mkdir -p dist && touch dist/.nojekyll



